In [1]:
import numpy as np

1. Write a NumPy program to test whether none of the elements of a given array is zero. 


In [2]:
def zero_checker(x):
    if bool(len(x[x==0])):
        print("Array contains zero element")
    else:
        print("Array does not have any zero elements")

def zero_check(x):
    return np.all(x!=0)

x=np.asarray([1,2,3,4,0])
r=np.asarray([1,2,3,4])

zero_checker(x)
zero_checker(r)

print(zero_check(x))
print(zero_check(r))

Array contains zero element
Array does not have any zero elements
False
True


2. Write a NumPy program to test whether any of the elements of a given array is non-zero.   


In [3]:
def num_checker(x):
    if bool(len(x[x!=0])):
        print("Array contains non-zero elements")
    else:
        print("Array does not have any non-zero elements")

def num_check(x):
    return np.all(x==0)

x=np.asarray([0,0,0,0,0])
r=np.asarray([0,0,3,0])

num_checker(x)
num_checker(r)

print(num_check(x))
print(num_check(r))

Array does not have any non-zero elements
Array contains non-zero elements
True
False


3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two 
given

In [4]:
def equal_with_tol(number,num,tol=None):
    return np.isclose(number,num,atol=tol)

x=5
y=5.2
tol=0.5
z=equal_with_tol(x,y,tol)
print(f"{x} is equal to {y} with tolerance = {tol}? {z}") #Check between 5 and 5.2      -0.5< 5-5.2 <0.5
y=5.6
z=equal_with_tol(x,y,tol)
print(f"{x} is equal to {y} with tolerance = {tol}? {z}")

5 is equal to 5.2 with tolerance = 0.5? True
5 is equal to 5.6 with tolerance = 0.5? False


4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [5]:
zer=np.zeros(10)
ones=np.ones(10)
fives=np.ones(10)*5
arr=np.concatenate((zer,ones,fives))
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. Write a NumPy program to create an array of the integers from 30 to 70.  


In [6]:
np.random.randint(30,70,size=10) # Array contains 10 numbers ranging from 30 to 70

array([68, 44, 52, 63, 46, 37, 32, 48, 43, 34])

6. Write a NumPy program to create a 3x3 identity matrix  


In [7]:
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7. Write a NumPy program to generate a random number between 0 and 1  


In [8]:
np.random.rand()

0.6200133420947426

8. Write a NumPy program to generate an array of 15 random numbers from a standard normal 
distribution  

In [9]:
np.random.randn(15)

array([-0.30399017, -0.37759651, -1.69129233, -0.12169349, -1.96032059,
       -0.17862792,  1.50217329, -0.60419016,  2.32166289,  1.04370506,
        0.13067291,  0.85898669,  0.56302504, -0.07546879,  0.47231997])

9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values 
except the first and last.   

In [10]:
x=np.random.randint(15,55,size=5)
x[1:-1]

array([44, 51, 53])

10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10  


In [11]:
np.random.randint(0, 11, size=5)


array([6, 9, 9, 3, 4])

11. Write a NumPy program to create a 5x5 matrix, in which the elements on the borders will be equal 
to 1, and inside 0.   

In [12]:
np.random.rand(5,5)

array([[0.72201298, 0.78702755, 0.4432692 , 0.6593375 , 0.87550674],
       [0.65243237, 0.78055896, 0.06154023, 0.38231179, 0.53200617],
       [0.92674864, 0.45587324, 0.38908512, 0.42794867, 0.13348261],
       [0.8679653 , 0.86620189, 0.38842169, 0.9171472 , 0.66841777],
       [0.07449041, 0.92319704, 0.10741345, 0.14346703, 0.49270565]])

12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 
3, 4, 5.  

In [16]:
zer=np.identity(5)
zer*=[1,2,3,4,5]
zer

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main 
diagonal. 

In [22]:
one=np.ones((4,4))
one-=np.diag([1,1,1,1])
one

array([[0., 1., 1., 1.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 1., 0.]])

14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) 
and load it.   

In [33]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.concatenate((x,y),axis=0)

np.savez_compressed(file="Amit-Mahmoud",args=z) #Saves into file

arr=np.load(file="Amit-Mahmoud.npz") #Reads from file
print(arr.files) #To print files in the files
arr['args']

['args']


array([1, 2, 3, 4, 5, 6])

15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. 
Select  

In [41]:
x=np.random.randint(0,41,size=40)
x

array([ 4,  7, 32,  1, 15, 40, 14, 17, 19, 27,  2, 19, 21,  0, 29, 17,  0,
        0, 22, 28, 34, 33, 17, 33,  9, 16, 37, 20, 14,  6, 24, 25, 24,  5,
       34, 33, 12, 22, 34, 26])

16. Write a NumPy program to extract all numbers from a given array which are less and greater than a 
specified number.   

In [47]:
minn=int(input("Enter lower bounder"))
maxx=int(input("Enter upper bounder"))
z=x[x>minn]
z=z[z<=maxx]
z

array([15, 14, 17, 19, 19, 17, 17, 16, 20, 14, 12])